### ISSUE TITLE
Cannot enable BetterExplostions

### ISSUE THREAD

**Issue by yukaling** [NicoXCoding/BetterExplosions#1]
I encountered an error when I starting up my server, here is **ERROR LOGS**:

`[21:05:59 ERROR]: Could not load 'plugins/BetterExplosions-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
        at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**DETAILS**
Plugin Version: 1.1
Minecraft Version: 1.18.2 Vanilla
ServerCore: Paper

I wonder how would I solve this question, thanks!

**Comment by Floodo** [comment]
I have the similiar error message

[13:03:06 ERROR]: Could not load 'plugins\BetterExplosions-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.8
        at org.bukkit.craftbukkit.v1_19_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[paper-1.19.jar:git-Paper-81]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:411) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:319) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

DETAILS
Plugin Version: 1.0-SNAPSHOT
Minecraft Version: 1.19 (only plugins)
ServerCore: git-Paper-81

**Comment by ynicoletti** [comment]
i just removed api restrictions: https://www.spigotmc.org/resources/betterexplosions.107733/
try with the latest version

**Comment by Floodo** [comment]
still same error :(

**Comment by ynicoletti** [comment]
you can message me on discord so we can troubleshoot this together?  Partofthegame#4692

**Comment by Floodo** [comment]
Issue solved in next version :)

**Comment by yukaling** [comment]
it's now working on 1.18.2! thanku! :D 💯
